package com.utilisuite.utilisuite.controllers;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.utilisuite.utilisuite.models.Quote;
import com.utilisuite.utilisuite.repositories.QuoteRepository;

@Controller
@CrossOrigin(origins = "*") // Adds CORS to entire controller for the specified url
@RequestMapping(path="/api/quotes")
public class QuoteController {
    @Autowired // This means to get the bean called userRepository
            // Which is auto-generated by Spring, we will use it to handle the data
    private QuoteRepository quoteRepository;

    // GET route for ALL quote ids, used in generating a random quote
    @GetMapping(path="/all-ids")
    public @ResponseBody int[] getAllIds() {
        Iterable<Quote> allQuotes = quoteRepository.findAll(); // finds all quotes
        int size = 0; // variable used to "count" how many quotes are found
        for (Quote i : allQuotes) { // iterates through allQuotes, essentially a FOR EACH quote
            size += 1;
        }
        
        int[] ids = new int[size]; // arrays in Java are defined of a specific size and cannot be changed
        int index = 0; // index used like a regular for loop, but wanted to iterate through allQuotes
        for (Quote entry : allQuotes) {
            // adds each id to the specified index
            ids[index] = entry.getId();
            index++;
        }

        // returns an array of all possible ids
        return ids;
    }

    // GET route for ALL quotes
    @GetMapping(path="")
    public @ResponseBody Iterable<Quote> getAllQuotes() {
        return quoteRepository.findAll();
    }

    // CREATE route for new quote
    @PostMapping(path="")
    public @ResponseBody Quote addNewQuote (@RequestBody Quote reqQuote) {
        // Creates new User
        Quote newQuote = new Quote();

        // Sets property values for new User
        newQuote.setAuthor(reqQuote.getAuthor());
        newQuote.setQuote(reqQuote.getQuote());

        return quoteRepository.save(newQuote);
    }

    // SHOW route for specific quote
    @GetMapping(path="/{id}")
    public @ResponseBody Optional<Quote> getQuote (@PathVariable int id) {
        return quoteRepository.findById(id);
    }

    // UPDATE route for specific quote
    @PutMapping(path="/{id}")
    public @ResponseBody Quote updateQuote (@PathVariable int id, @RequestBody Quote reqQuote) {
        Quote newQuote = reqQuote;
        newQuote.setId(id);
        return quoteRepository.save(newQuote);
    }

    // DELETE route for specific quote
    @DeleteMapping(path="/{id}")
    public @ResponseBody String deleteQuote (@PathVariable int id) {
        quoteRepository.deleteById(id);
        return "deleted...";
    }
}
